import { AboutSlint, VerticalBox } from "std-widgets.slint";

export component Entity {
    in-out property <length> p_x;
    in-out property <length> p_y;

    callback send_current([length]);

    Rectangle {
        width: 50px;
        height: 50px;
        x <=> p_x;
        y <=> p_y;
        border-width: 2px;
        border-color: rgb(237, 202, 222);
        border-radius: 600px;
        background: rgb(224, 65, 158);
    }
}

export component Target {
    in-out property <length> pp_x:0px;
    in-out property <length> pp_y:0px;

    Rectangle {
        x <=> pp_x;
        y <=> pp_y;
        border-width: 2px;
        width: 20px;
        height: 20px;
        border-color: rgb(236, 209, 240);
        border-radius: 60px;
        background: rgb(226, 138, 237);
    }

}

export component MainWindow inherits Window {
    in-out property <length> g_x;
    in-out property <length> g_y;

    in-out property <length> t_x:6000px;
    in-out property <length> t_y:6000px;



    Entity {
        p_x <=> g_x;
        p_y <=> g_y;
    }
    Target {
        pp_x <=> t_x;
        pp_y <=> t_y;
    }
    
    
}
